### ISSUE TITLE
What to do when the module no longer loads on Foundry v10

### ISSUE THREAD

**Issue by oestred** [krbz999/concentrationnotifier#40]
During our session last night I noticed concentration notifier didn't work. Today I checked and it wasn't showing any more. Checked the setup screen and it has it installed but it says it requires V11 do does not load in V10 any more.
 I am waiting until more modules update to go to V11 in the future. Can it be marked to min V10 or do I need to install an old version meanwhile?
 Very hand module by the way, thank you for your work on it!

 Thank you

**Comment by krbz999** [comment]
Which version?

**Comment by oestred** [comment]
the latest 11.0.2. Foundry v10, D&D ver 2.1.5 (have not upgraded it yet, figured will wait until go to v11). 

I did just manually download ver 10.2.0 of the module and that works so could be a work around for now.

**Comment by krbz999** [comment]
The latest v10 version is what you should be using unless you update the system to 2.2.x. I originally planned for future releases to be for v11 only, but due to the system backporting breaking changes I had to make them compatible with both v10 and v11 to fix critical errors.

In short: Up to and including dnd5e 2.1.5: Use CN v10.2.0. If later, use the most recent version of the module.

**Comment by oestred** [comment]
Awesome, that works. Thank you for the confirmation!

**Comment by krbz999** [comment]
As we near the end of v11, I feel this no longer needs to be pinned. The adoption rate of the newest core edition has been quite high.
